VERSION 0.8

PROJECT blue-build/earthly-lib

IMPORT github.com/earthly/lib/utils/dind AS dind

build:
	FROM rust
	RUN apt-get update && \
		apt-get install -y musl-dev musl-tools jq && \
		rustup component add clippy && \
		rustup target add x86_64-unknown-linux-musl

	RUN cargo install --root $CARGO_HOME --locked cargo-sweep git-cliff cargo-release

	DO dind+INSTALL
	SAVE IMAGE --push ghcr.io/blue-build/earthly-lib/cargo-builder
