name: Earthly PR +build

on:
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: earthly/actions-setup@v1

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.ref }}

      - name: Run build
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          earthly --ci -P +all


