name: Earthly main branch +all

concurrency: 
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

on:
  schedule:
    - cron: "00 17 * * *" # build at 17:00 UTC every day
  workflow_dispatch:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 1

jobs:
  build:
    permissions:
      packages: write
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: earthly/actions-setup@v1

      # Setup repo and add caching
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          earthly --push --ci -P +all
